sudo: false
dist: trusty
language: java
jvm: oraclejdk11
cache:
 directories:
   - $HOME/.m2
install: true
script: 
  - mvn clean verify cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
