[push_int_constant]
opcode=0
large=true

[push_string_constant]
opcode=3
large=true

[push_long_constant]
opcode=-1
large=true

[pop_int_discard]
opcode=38
large=false

[pop_string_discard]
opcode=39
large=false

[pop_long_discard]
opcode=-1
large=false

[push_int_local]
opcode=33
large=true

[push_string_local]
opcode=35
large=true

[push_long_local]
opcode=-1
large=true

[pop_int_local]
opcode=34
large=true

[pop_string_local]
opcode=36
large=true

[pop_long_local]
opcode=-1
large=true

[push_varp]
opcode=1
large=true

[push_varp_bit]
opcode=25
large=true

[push_varc_int]
opcode=42
large=true

[push_varc_string]
opcode=49
large=true

[pop_varp]
opcode=2
large=true

[pop_varp_bit]
opcode=27
large=true

[pop_varc_int]
opcode=43
large=true

[pop_varc_string]
opcode=50
large=true

[define_array]
opcode=44
large=true

[push_array_int]
opcode=45
large=true

[pop_array_int]
opcode=46
large=true

[branch]
opcode=6
large=true

[branch_equals]
opcode=8
large=true

[branch_not]
opcode=7
large=true

[branch_less_than]
opcode=9
large=true

[branch_greater_than]
opcode=10
large=true

[branch_less_than_or_equals]
opcode=31
large=true

[branch_greater_than_or_equals]
opcode=32
large=true

[branch_if_true]
opcode=-1
large=true

[branch_if_false]
opcode=-1
large=true

[long_branch_equals]
opcode=-1
large=true

[long_branch_not]
opcode=-1
large=true

[long_branch_less_than]
opcode=-1
large=true

[long_branch_greater_than]
opcode=-1
large=true

[long_branch_less_than_or_equals]
opcode=-1
large=true

[long_branch_greater_than_or_equals]
opcode=-1
large=true

[switch]
opcode=60
large=true

[return]
opcode=21
large=false

[join_string]
opcode=37
large=true

[jump_with_params]
opcode=80
large=true

[gosub_with_params]
opcode=40
large=true

[add]
opcode=4000
large=false

[sub]
opcode=4001
large=false

[mul]
opcode=4002
large=false

[div]
opcode=4003
large=false

[mod]
opcode=4011
large=false