[mes]
opcode=3100
arguments=["STRING"]

[add]
opcode=4000
type=["INT"]
arguments=["INT","INT"]

[sub]
opcode=4001
type=["INT"]
arguments=["INT","INT"]

[mul]
opcode=4002
type=["INT"]
arguments=["INT","INT"]

[div]
opcode=4003
type=["INT"]
arguments=["INT","INT"]

[random]
opcode=4004
type=["INT"]
arguments=["INT"]

[randominc]
opcode=4005
type=["INT"]
arguments=["INT"]

[interpolate]
opcode=4006
type=["INT"]
arguments=["INT", "INT", "INT", "INT", "INT"]