[proc]
operator="tilde"
opcode="gosub_with_params"
support_return=true
support_arguments=true

[label]
operator="at"
opcode="jump_with_params"
support_return=false
support_arguments=true

[if_button1]
support_return=false
support_argument=false

[if_button2]
support_return=false
support_argument=false

[if_button3]
support_return=false
support_argument=false

[if_button4]
support_return=false
support_argument=false

[if_button5]
support_return=false
support_argument=false

[if_button6]
support_return=false
support_argument=false

[if_button7]
support_return=false
support_argument=false

[if_button8]
support_return=false
support_argument=false

[if_button9]
support_return=false
support_argument=false

[if_button10]
support_return=false
support_argument=false